on:
  rss:
    url:
      - https://rsshub-madiffnx.cloud.sealos.io/zhihu/people/activities/ji-qi-zhi-xin-65
      - https://rsshub-madiffnx.cloud.sealos.io/zhihu/people/activities/liang-zi-wei-48
      - https://rsshub-madiffnx.cloud.sealos.io/zhihu/people/activities/xin-zhi-yuan-88-3
      - https://rsshub-madiffnx.cloud.sealos.io/zhihu/people/activities/zhang-jun-87-61
      - https://papers.cool/arxiv/cs.IR/feed
jobs:
  request:
    name: Make a HTTP Request
    runs-on: ubuntu-latest
    steps:
      - name: Set folder for RSS 1
        if: ${{ contains('https://rsshub.app/zhihu/people/activities/ji-qi-zhi-xin-65,https://rsshub.app/zhihu/people/activities/liang-zi-wei-48,https://rsshub.app/zhihu/people/activities/xin-zhi-yuan-88-3,https://rsshub.app/zhihu/people/activities/zhang-jun-87-61', on.rss.url) }}
        run: echo "::set-output name=folder::AI三大会"

      - name: Set folder for RSS 2
        if: ${{ on.rss.url == 'https://papers.cool/arxiv/cs.IR/feed' }}
        run: echo "::set-output name=folder::Arxiv-IR"

      - name: Make a HTTP Request
        uses: actionsflow/axios@v1
        with:
          url: https://cubox.pro/c/api/save/a7pC7Aspd92
          method: POST
          body: |
            {
              "type":"url",
              "content":"${{ on.rss.outputs.link }}", 
              "title": "${{ on.rss.outputs.title }}",
              "folder":"${{ steps.request.outputs.folder }}"
            }
